spring:
  datasource:
    url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DB}
    username: ${PG_USER}
    password: ${PG_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false
  sql:
    init:
      mode: always
      data-locations: classpath:data-init-schema.sql

telegram:
  botName: otv-lab4
  token: ${BOT_TOKEN}
